// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlite

import ()

type Todo struct {
	ID       string
	Task     string
	Created  int64
	Updated  int64
	Complete string
	Rank     int64
}
